import { access, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { App } from "@/lib/types";

const DEFAULT_NODE_MAJOR = 24;

type PackageManager = "npm" | "pnpm" | "yarn";

interface PackageJson {
  main?: string;
  scripts?: Record<string, string>;
  engines?: { node?: string };
  packageManager?: string;
}

export interface BuildPlan {
  dockerfile: string;
  /** True when Grove wrote the Dockerfile; it then reads build-time env from the grove_env secret. */
  generated: boolean;
  summary: string;
}

async function exists(file: string): Promise<boolean> {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
}

/**
 * Uses the repository's own Dockerfile when there is one. Otherwise writes a Dockerfile
 * for a Node.js app, similar to what a Heroku buildpack would do.
 */
export async function prepareBuild(dir: string, app: App): Promise<BuildPlan> {
  const ownDockerfile = path.join(dir, "Dockerfile");
  if (await exists(ownDockerfile)) {
    return { dockerfile: ownDockerfile, generated: false, summary: "Building with the repository's Dockerfile" };
  }

  const packageJsonPath = path.join(dir, "package.json");
  if (!(await exists(packageJsonPath))) {
    throw new Error(
      "No package.json or Dockerfile at the repository root. Grove builds Node.js apps, or anything with a Dockerfile.",
    );
  }

  const pkg = JSON.parse(await readFile(packageJsonPath, "utf8")) as PackageJson;
  const pm: PackageManager = (await exists(path.join(dir, "pnpm-lock.yaml")))
    ? "pnpm"
    : (await exists(path.join(dir, "yarn.lock")))
      ? "yarn"
      : "npm";
  const npmLockfile =
    (await exists(path.join(dir, "package-lock.json"))) ||
    (await exists(path.join(dir, "npm-shrinkwrap.json")));
  const pinned = pkg.packageManager?.match(/^(npm|pnpm|yarn)@([0-9][^+\s]*)/);
  const pmVersion = pinned && pinned[1] === pm ? pinned[2] : null;
  const nodeMajor = await detectNodeMajor(dir, pkg);
  const build = app.buildCommand ?? (pkg.scripts?.build ? `${pm} run build` : null);
  // npm can run any package.json script, so the runtime image doesn't need pnpm or yarn.
  const start = pkg.scripts?.start ? "npm start" : `node ${pkg.main ?? "index.js"}`;

  const dockerfile = renderDockerfile({ nodeMajor, pm, pmVersion, npmLockfile, build, start });
  const dockerfilePath = path.join(dir, ".grove.Dockerfile");
  await writeFile(dockerfilePath, dockerfile);
  if (!(await exists(path.join(dir, ".dockerignore")))) {
    await writeFile(path.join(dir, ".dockerignore"), ".git\nnode_modules\nnpm-debug.log*\n");
  }

  const parts = [
    `Node.js ${nodeMajor}`,
    pmVersion ? `${pm} ${pmVersion}` : pm,
    build ? `build: ${build}` : "no build step",
    `start: ${app.startCommand ?? start}`,
  ];
  return {
    dockerfile: dockerfilePath,
    generated: true,
    summary: `No Dockerfile in the repo, so Grove generated one (${parts.join(" · ")})`,
  };
}

function renderDockerfile(options: {
  nodeMajor: number;
  pm: PackageManager;
  pmVersion: string | null;
  npmLockfile: boolean;
  build: string | null;
  start: string;
}): string {
  const { nodeMajor, pm, pmVersion, npmLockfile, build, start } = options;
  // The app's env vars arrive as a build secret: available to install and build, never stored in a layer.
  const withEnv = "--mount=type=secret,id=grove_env";
  const loadEnv = "if [ -f /run/secrets/grove_env ]; then . /run/secrets/grove_env; fi &&";

  const setup = {
    npm: [],
    pnpm: [`RUN npm install --global pnpm@${pmVersion ?? "9"}`],
    yarn: [
      pmVersion && !pmVersion.startsWith("1.")
        ? "RUN npm install --global corepack && corepack enable"
        : "RUN command -v yarn >/dev/null || npm install --global yarn",
    ],
  }[pm];
  const install = {
    npm: `RUN --mount=type=cache,target=/root/.npm ${withEnv} ${loadEnv} ${npmLockfile ? "npm ci" : "npm install"}`,
    pnpm: `RUN --mount=type=cache,target=/root/.local/share/pnpm/store ${withEnv} ${loadEnv} pnpm install --frozen-lockfile`,
    yarn: `RUN --mount=type=cache,target=/usr/local/share/.cache/yarn ${withEnv} ${loadEnv} yarn install`,
  }[pm];

  return [
    "# Generated by Grove. Commit a Dockerfile to your repo to take full control of the build.",
    `FROM node:${nodeMajor} AS build`,
    "WORKDIR /app",
    // Apps are built like on Heroku: dependency install scripts run, and CI tooling stays quiet.
    "ENV CI=true NEXT_TELEMETRY_DISABLED=1 npm_config_dangerously_allow_all_scripts=true npm_config_update_notifier=false npm_config_fund=false npm_config_audit=false",
    ...setup,
    "COPY . .",
    install,
    ...(build ? [`RUN ${withEnv} ${loadEnv} ${build}`] : []),
    ...(pm === "npm" ? ["RUN npm prune --omit=dev"] : []),
    "",
    `FROM node:${nodeMajor}-slim`,
    "WORKDIR /app",
    "ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1",
    "COPY --from=build --chown=node:node /app ./",
    "USER node",
    `CMD ["sh", "-c", ${JSON.stringify(execPrefixed(start))}]`,
    "",
  ].join("\n");
}

/** `exec` hands PID 1's signals straight to the app, unless the command chains several steps. */
export function execPrefixed(command: string): string {
  return /[;&|]/.test(command) ? command : `exec ${command}`;
}

/** Writes env vars as a shell script the generated Dockerfile sources during the build. */
export function buildEnvScript(env: Record<string, string>): string {
  return Object.entries(env)
    .map(([key, value]) => `export ${key}='${value.replaceAll("'", `'\\''`)}'`)
    .join("\n");
}

async function detectNodeMajor(dir: string, pkg: PackageJson): Promise<number> {
  for (const file of [".nvmrc", ".node-version"]) {
    try {
      const match = (await readFile(path.join(dir, file), "utf8")).trim().match(/^v?(\d+)/);
      if (match) return Number(match[1]);
    } catch {
      // Not present.
    }
  }

  const range = pkg.engines?.node;
  if (!range) return DEFAULT_NODE_MAJOR;
  const majors = range
    .split(/\|\||\s+/)
    .map((token) => token.match(/(\d+)/)?.[1])
    .filter((major): major is string => Boolean(major))
    .map(Number);
  if (majors.length === 0) return DEFAULT_NODE_MAJOR;
  if (majors.includes(DEFAULT_NODE_MAJOR)) return DEFAULT_NODE_MAJOR;
  const highest = Math.max(...majors);
  const openEnded = />/.test(range) && !/</.test(range);
  return openEnded ? Math.max(highest, DEFAULT_NODE_MAJOR) : highest;
}
